name: news force
author: John Wass
description: Enforce changelog entries on pull requests
branding:
  icon: book-open
  color: green

inputs:
  article_dir:
    description: Directory containing news fragments
    required: true
    default: news
  categories:
    description: List of change categories
    required: true
    default: added,removed,changed,fixed,packaging
  ignores:
    description: List of labels to ignore
    required: true
    default: ci,doc,release
  contrib_url:
    description: URL of contribution guide
    required: false
    default: ""

runs:
  using: docker
  image: Dockerfile
