name: news check
author: John Wass
description: Action for changelog management
branding:
  icon: book-open
  color: green

inputs:
  article_dir:
    description: Directory containing news fragments
    required: true
    default: news
  categories:
    description: List of change categories
    required: true
    default: added,removed,changed,fixed,build
  ignores:
    description: List of labels to ignore
    required: true
    default: release,documentation
  contrib_url:
    description: URL of contribution guide
    required: false
    default: ''


runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
         cache: 'pip'
    - shell: bash
      run: pip install -r requirements.txt
    - shell: bash
      run: |
        python check.py --categories=${{ inputs.categories }} \
                        --ignores=${{ inputs.ignores }} \
                        --contrib_guide_url=${{ inputs.contrib_url }} \
                        ${{ inputs.article_dir }}
