name: ci

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: test0
        uses: ./
        with:
          article_dir: test/news0
        env:
          EVENT_PATH: test/e0.json

      - name: test1
        uses: ./
        with:
          article_dir: test/news1
        env:
          EVENT_PATH: test/e1.json
